### ISSUE TITLE
Request:  __contains__ and __getitem__ interfaces

### ISSUE THREAD

**Issue by bjmgeek** [wbolster/plyvel#26]
Assuming db is instance of plyvel.DBInterface, it would be useful to do something like:

db['key']

or 

if 'key' in db

**Comment by wiegerw** [comment]
I just lost an hour because I did not expect that the syntax `key in db` doesn't work the same as with dictionaries. To me this was so unexpected, that it was the last thing that I looked at when debugging my code. The argument that this check promotes bad practice (`if key in db: do_something(db[key])`) is debatable: this equally applies to dictionaries.

**Comment by wbolster** [comment]
ouch, at first i thought that your comment didn't make any sense, since `thing in db` is not supposed to work at all since plyvel does _not_ offer a dict-like interface…

… until it occurred to me that ‘dict-like’ involves more than `__getitem__`, `__setitem__`, and `__delitem__`, etc.

notably, the ‘in’ operator has fallback behaviour for objects that do not specify `__contains__`, see the [section about `inthe `in` operator in the language reference](https://docs.python.org/3/reference/expressions.html#membership-test-details):

- `__contains__` ← not present on `plyvel.DB`
- `__iter__` ← present on `plyvel.DB` 
- `__getitem__` ← not present on `plyvel.DB`

the `in` operator _accidentally_ triggers the `__iter__` behaviour!

this means that `thing in db` actually iterates over the db, which yields `(key, value)` pairs, none of which will match `thing`. for comparison, `(key, value) in db` actually works… _accidentally_! for non-matches such as an innocent looking key lookup the whole database is iterated (extremely slow for larger databases), and will always return `False` in the end.

not good 😨

that said, i stand by my 10+ year old opinion that `plyvel.DB` (and iterators, and prefixed `DB`, etc.) should _not_ offer `__contains__` and `__getitem__` to suggest a dict-like interface. it's not just the performance anti-pattern, but also other expectations like `.keys()`, `thing in db`, `iter(db)` yielding just keys (not the case in plyvel!), etc.

my proposed solution is to explicitly break `thing in db` by adding a `__contains__` method to each relevant class that will simply raise `TypeError`.

wdyt? @wiegerw

**Comment by wiegerw** [comment]
@wbolster I agree that it is best to explicitly forbid the syntax `key in db`, since the current behavior is quite unexpected.

Personally I would like to see an interface that is as close to dictionaries as possible. But I understand now that there are important differences between the two, and then it makes sense to be careful with this.
