### ISSUE TITLE
Async api?

### ISSUE THREAD

**Issue by anirudh-chhangani** [wbolster/plyvel#92]
Having async/await support would be great!

**Comment by maheshnayer** [comment]
+1

**Comment by wbolster** [comment]
i am not planning to work on this.

since leveldb itself is a synchronous library, at its core this will involve blocking calls to leveldb in any case. i think this means some threading mechanism is needed anyway to run the plyvel/leveldb code in a background thread.

plyvel _does_ release the global interpreter lock (gil) around most relevant calls into the leveldb api, so that would mean the python runtime can do other things while waiting.

so, if people are interested in this, some wrapper layer around plyvel seems the way to go. whether that layer lives inside or outside the plyvel codebase is a technical detail that shouldn't change the overall approach.
